### ISSUE TITLE
Generos con el autor, familias

### ISSUE THREAD

**Issue by seraliam** [Ghini/ghini.pocket#29]
Hablando del panel de corrección e inserción datos:

Me sería muy útil que también al consultar el género me indique a que familia pertenece.

**Comment by mfrasca** [comment]
sí, tenía la duda si fuese el autor, o la familia, lo más útil, o sea que ya estaba trabajando en la misma dirección que indicas.  pero es que no hay tanto espacio como para poner ambos.  qué opinas de esta opción?

![image](https://user-images.githubusercontent.com/122869/38257103-46684e3a-3725-11e8-87ab-dec57086a704.png)
![image](https://user-images.githubusercontent.com/122869/38257360-b2ee0798-3725-11e8-8e3d-5c8bd3f47391.png)

nota que los resultados literales están antes de los resultados fonéticos, y los dos grupos están en orden alfabético.

**Comment by mfrasca** [comment]
sorry, wrong commit text.  should have been "inform user of family or accepted name when choosing completion"
pienso podemos cerrar el issue, cierto?  ahora se trata de poner los datos revisados en la base datos de pocket, para que aparezca en la página de los resultados, es la issue #25.  lo que incluye la familia.

**Comment by seraliam** [comment]
Me parece muy bien la forma como lo presentas para indicar la familia a la que pertenece.

**Comment by mfrasca** [comment]
No estoy cierto que hacer con los sinónimos: al momento sólo se te indica, éste es un sinónimo y éste es el correspondiente epíteto aceptado, como en 
![image](https://user-images.githubusercontent.com/122869/38261605-4f10f806-3730-11e8-88c8-15ecb5405870.png)

Pero si quieres ir al aceptado, tienes que escribirlo tú, o sea borrar lo que ya pusiste y empezar con la sugerencia recibida. Y la sugerencia desaparece en el mismo momento en que empiezas a tipear el nuevo epíteto. Me parece aceptable, pero no sé, habrá que evaluarlo.
