### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by comradekingu** [Ghini/ghini.pocket#31]
License only says "Copying".

**Comment by mfrasca** [comment]
:rofl: I was also for a moment baffled. no, no: `LICENSE` is a symbolic link to `COPYING`, so in github it will not show real content, it shows the name of the target of the symbolic link.  but you're right, it can be confusing.  I will check what are the most common practices regarding LICENSE and COPYING, and put in both of them the least surprising text.

**Comment by mfrasca** [comment]
seems practice is either/or, not both. and [within gnu, it's `COPYING`](https://www.gnu.org/licenses/gpl-howto.html).

**Comment by mfrasca** [comment]
well, we could also have a `LICENSE` file adapting the statement » In GNU programs we conventionally put the license in a file called COPYING.«, but we can also have no `LICENSE` file and only `COPYING`. I'm fine with both options.
